Repository CoVital-Project/pulse-ox-data-collection-web-service, pull requests merged in 2020-03, with the labels that each got.

#13 adds github automerge
  .github/workflows/automerge.yml
Labels: auto-rebase-and-merge-when-passing

#15 Fixes automerge to handle separate "auto update" and "merge when passing" use cases
  .github/workflows/automerge.yml
  CODEOWNERS
Labels: auto-rebase, merge-when-passing

#16 Allows automerge from external forks
  .github/workflows/automerge.yml
Labels: auto-rebase, merge-when-passing

#12 Updates user.js model to include some additional fields and timestamps
  src/model/user.js
Labels: auto-rebase, merge-when-passing

#17 Add names to readme
  README.md
Labels: merge-when-passing

#18 Spike out a functioning Dockerfile
  .dockerignore
  Dockerfile
Labels: merge-when-passing

#22 Updates CI to include eslint/prettier/jest via babel
  .eslintignore
  .eslintrc.json
  .github/workflows/ci.yml
  .gitignore
  README.md
  migrations/1585079645680-first-user.js
  package-lock.json
  package.json
  src/app.js
  src/config/db.js
  src/controller/user.js
  src/model/user.js
  src/route/user.js
Labels: merge-when-passing

#23 Add Docker build step to CI run
  .github/workflows/ci.yml
Labels: merge-when-passing

#24 Push master builds to docker hub
  .github/workflows/release.yml
  script/docker-publish.sh
Labels: merge-when-passing

#25 Remove manual 'master' docker tag cause it looks like the GHA will do…
  .github/workflows/release.yml
Labels: merge-when-passing

#27 Slims down docker image, couldn't make alpine respect the in-memory m…
  Dockerfile
  script/docker-build.sh
Labels: merge-when-passing

#28 Try again to autorelease to docker after successful master merges
  .github/workflows/release.yml
Labels: merge-when-passing

#29 Try again to autorelease to docker after successful master merges
  .github/workflows/release.yml
Labels: merge-when-passing
